Repository 8hk/AEK, pull requests merged in 2020-12, with the labels that each got.

#44 Docker
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  manage.py
  mentisparchment_docker/__init__.py
  mentisparchment_docker/asgi.py
  mentisparchment_docker/settings.py
  mentisparchment_docker/urls.py
  mentisparchment_docker/wsgi.py
  mongo-app/.gitkeep
  mongo-data/.gitkeep
  requirements.txt
Labels: database, development, feature, infrastructure

#45 Ontology retrieval via BioPortal
  OntologyRetriever/ontology_retriever.py
Labels: development, feature

#69 Annotate article
  OntologyRetriever/annotate_abstract.py
Labels: development, feature

#67 Search Page Front-End
  README.md
  fe/css/bootstrap-tagsinput.css
  fe/css/custom/search.css
  fe/html/index.html
  fe/js/bootstrap-tagsinput.js
  fe/js/custom/search.js
Labels: development, feature, front-end

#65 Main Query Class
  api/mainquery/__init__.py
  api/mainquery/admin.py
  api/mainquery/apps.py
  api/mainquery/migrations/__init__.py
  api/mainquery/models.py
  api/mainquery/tests.py
  api/mainquery/views.py
Labels: development, feature

#72 Annotate article
  OntologyRetriever/annotate_abstract.py
  OntologyRetriever/concepts.pickle
  requirements.txt
Labels: development, feature

#73 Integrate Search Front-End and Back-End
  api/search/views.py
  docker-compose.yml
  mentisparchment_docker/settings.py
  mentisparchment_docker/urls.py
  static/css/.DS_Store
  static/css/bootstrap-tagsinput.css
  static/css/custom/search.css
  static/html/index.html
  static/js/.DS_Store
  static/js/bootstrap-tagsinput.js
  static/js/custom/search.js
Labels: development, feature, front-end

#74 Summary page fe be
  .gitignore
  api/search/views.py
  fe/css/all.min.css
  fe/css/bootstrap-solid.svg
  fe/css/bootstrap.css
  fe/css/bootstrap.min.css
  fe/css/custom/card.css
  fe/html/summary-page.html
  fe/js/bootstrap.min.js
  fe/js/chart.js-2.9.4/package/LICENSE.md
  fe/js/chart.js-2.9.4/package/README.md
  fe/js/chart.js-2.9.4/package/bower.json
  fe/js/chart.js-2.9.4/package/composer.json
  fe/js/chart.js-2.9.4/package/dist/Chart.bundle.js
  fe/js/chart.js-2.9.4/package/dist/Chart.bundle.min.js
  fe/js/chart.js-2.9.4/package/dist/Chart.css
  fe/js/chart.js-2.9.4/package/dist/Chart.js
  fe/js/chart.js-2.9.4/package/dist/Chart.min.css
  fe/js/chart.js-2.9.4/package/dist/Chart.min.js
  fe/js/chart.js-2.9.4/package/npm-debug.log
  fe/js/chart.js-2.9.4/package/package.json
  fe/js/custom/keyword_pair.js
  fe/js/holder.min.js
  fe/js/jquery-slim.min.js
  fe/js/popper.min.js
  fe/js/shieldui-all.min.js
  mentisparchment_docker/settings.py
  mentisparchment_docker/urls.py
  requirements.txt
Labels: development, feature
