Repository 8hk/AEK, pull requests merged in 2021-01, with the labels that each got.

#78 Detailed search result
  OntologyRetriever/annotate_abstract.py
Labels: database, development, feature, high

#80 Full Text Search
  Dockerfile
  annotator_tool/annotate_abstract.py
  annotator_tool/concepts.pickle
  annotator_tool/import_articles_to_elasticsearch.py
  annotator_tool/ontology_retriever.py
  api/search/views.py
  docker-compose.yml
  mentisparchment_docker/urls.py
  postman-collection/mentis.postman_collection.json
  requirements.txt
Labels: database, development, feature

#82 Annotator service
  annotator_tool/annotate_abstract.py
  api/search/templatetags/filters.py
  api/search/views.py
  mentisparchment_docker/urls.py
  static/html/article.html
Labels: database, development, feature, front-end

#84 Data transfer result page
  README.md
  annotator_tool/annotate_abstract.py
  annotator_tool/create_index.py
  api/search/views.py
  static/html/summary-page.html
  static/js/shieldui-all.min.js
Labels: backend, development, feature, high

#87 Detailed search summary
  annotator_tool/annotate_abstract.py
  api/search/views.py
  static/css/custom/card.css
  static/css/custom/datatable.css
  static/html/summary-page.html
  static/js/custom/keyword_pair.js
Labels: feature

#89 bugfix of duplicate article problem #81
  api/search/views.py
Labels: bug, high

#88 Clickable feature is added for pubmed and article links
  static/js/custom/keyword_pair.js
Labels: feature

#92 empty result list feature commit
  api/search/views.py
  static/css/custom/empty-list.css
  static/html/summary-page.html
  static/js/custom/keyword_pair.js
Labels: backend, feature, front-end

#98 About Page
  api/search/views.py
  api/views.py
  mentisparchment_docker/urls.py
  static/css/custom/about.css
  static/css/custom/counter.css
  static/html/about.html
  static/html/index.html
Labels: backend, development, feature, front-end

#97 search improvement
  api/search/views.py
  static/js/custom/keyword_pair.js
Labels: backend, development, feature

#100 Change the annotation structure for synonyms. Change the search accor…
  annotator_tool/annotate_abstract.py
  api/search/models.py
  api/search/views.py
Labels: database, development

#99 descriptive tags are added to emphasize dimensions
  api/search/views.py
  static/html/summary-page.html
  static/js/custom/keyword_pair.js
Labels: development

#106 Search wikidata
  annotator_tool/annotate_abstract.py
  api/search/views.py
  static/css/custom/about.css
  static/css/custom/common.css
  static/html/about.html
  static/html/article.html
  static/html/index.html
  static/html/summary-page.html
  static/js/custom/keyword_pair.js
  static/js/custom/search.js
  static/js/custom/search_wikidata.js
Labels: development, feature, front-end
