Repository 8hk/AEK, pull requests merged in 2021-02, with the labels that each got.

#107 number of authors in the search results fixed to 5
  static/js/custom/keyword_pair.js
Labels: development

#108 Elasticsearch Improvement
  api/search/views.py
  static/html/summary-page.html
  static/js/custom/keyword_pair.js
  static/js/custom/search.js
Labels: backend, database, development, feature

#111 Tests
  README.md
  api/search/tests.py
  coverage_report.txt
Labels: development, documentation

#119 annotate retrievel bugfixes
  annotator_tool/annotate_abstract.py
Labels: backend, bug, development
